In [1]:
from keras.preprocessing.text import one_hot

Using TensorFlow backend.


In [2]:
sent=['the sun is too hot',
     'i love indian army',
     'my birthday in august',
     'i drink milk much',
     'these are the examples',
     'i am a developer',
      'i am good boy',
     'the table is yellow']

In [3]:
sent

['the sun is too hot',
 'i love indian army',
 'my birthday in august',
 'i drink milk much',
 'these are the examples',
 'i am a developer',
 'i am good boy',
 'the table is yellow']

In [4]:
voc_size=10000   #vocublary

# one hot representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[6088, 2491, 6834, 6395, 8535], [2214, 9000, 8277, 8484], [5889, 8397, 503, 7780], [2214, 4122, 6421, 4123], [5406, 9793, 6088, 5708], [2214, 2133, 9400, 1553], [2214, 2133, 8365, 3560], [6088, 4125, 6834, 5427]]


# word embedding

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 6088 2491 6834 6395 8535]
 [   0    0    0    0 2214 9000 8277 8484]
 [   0    0    0    0 5889 8397  503 7780]
 [   0    0    0    0 2214 4122 6421 4123]
 [   0    0    0    0 5406 9793 6088 5708]
 [   0    0    0    0 2214 2133 9400 1553]
 [   0    0    0    0 2214 2133 8365 3560]
 [   0    0    0    0 6088 4125 6834 5427]]


In [9]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[ 2.29020379e-02 -1.83589235e-02 -1.09268352e-03  1.63835399e-02
    1.00547187e-02 -4.84172255e-03 -3.82544622e-02  2.36971118e-02
    4.49098274e-03 -3.29502225e-02]
  [ 2.29020379e-02 -1.83589235e-02 -1.09268352e-03  1.63835399e-02
    1.00547187e-02 -4.84172255e-03 -3.82544622e-02  2.36971118e-02
    4.49098274e-03 -3.29502225e-02]
  [ 2.29020379e-02 -1.83589235e-02 -1.09268352e-03  1.63835399e-02
    1.00547187e-02 -4.84172255e-03 -3.82544622e-02  2.36971118e-02
    4.49098274e-03 -3.29502225e-02]
  [ 6.02866337e-03  4.55704816e-02 -2.11672671e-02 -1.19212493e-02
   -2.81532295e-02  1.37212314e-02 -2.58280877e-02  4.20319326e-02
    4.26230468e-02 -1.30840056e-02]
  [-4.37178724e-02 -1.85922384e-02 -3.41784209e-04  4.22773100e-02
    4.76969816e-02  2.82268263e-02 -1.43559463e-02 -3.65672000e-02
    4.29789536e-02 -4.73058335e-02]
  [-2.15356424e-03 -4.35221195e-03  1.78700574e-02  4.18605469e-02
   -5.74268401e-04  3.41490768e-02 -3.69006172e-02  1.55125745e-02
   -1.73078850e-

In [14]:
embedded_docs[0]

array([   0,    0,    0, 6088, 2491, 6834, 6395, 8535])

In [15]:
print(model.predict(embedded_docs))[0]

[[[ 2.29020379e-02 -1.83589235e-02 -1.09268352e-03  1.63835399e-02
    1.00547187e-02 -4.84172255e-03 -3.82544622e-02  2.36971118e-02
    4.49098274e-03 -3.29502225e-02]
  [ 2.29020379e-02 -1.83589235e-02 -1.09268352e-03  1.63835399e-02
    1.00547187e-02 -4.84172255e-03 -3.82544622e-02  2.36971118e-02
    4.49098274e-03 -3.29502225e-02]
  [ 2.29020379e-02 -1.83589235e-02 -1.09268352e-03  1.63835399e-02
    1.00547187e-02 -4.84172255e-03 -3.82544622e-02  2.36971118e-02
    4.49098274e-03 -3.29502225e-02]
  [ 6.02866337e-03  4.55704816e-02 -2.11672671e-02 -1.19212493e-02
   -2.81532295e-02  1.37212314e-02 -2.58280877e-02  4.20319326e-02
    4.26230468e-02 -1.30840056e-02]
  [-4.37178724e-02 -1.85922384e-02 -3.41784209e-04  4.22773100e-02
    4.76969816e-02  2.82268263e-02 -1.43559463e-02 -3.65672000e-02
    4.29789536e-02 -4.73058335e-02]
  [-2.15356424e-03 -4.35221195e-03  1.78700574e-02  4.18605469e-02
   -5.74268401e-04  3.41490768e-02 -3.69006172e-02  1.55125745e-02
   -1.73078850e-

TypeError: 'NoneType' object is not subscriptable